version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: kakerusaman
      POSTGRES_PASSWORD: kakerusaman123
      POSTGRES_DB: kakerusamandatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: